qps: avoid endless snapshot failure
(related to a65b7f45c7960ec0ed6788be59d12d65991c725c qps: on-disk data are
read-only.)
If snapshot fails in qps_map_pg_snapshot() between
fd = x_openat(qps->dfd, buf, O_RDWR | O_TRUNC | O_CREAT, 0444);
and
if (gzclose(out)) {

we could finish with an read-only file and all following snapshot tries will
end on:
error: QPS: snapshotter-child: unexpected I/O error (openat:Permission
denied)
(due to this open(...RDWR...)).

This patch creates the file 644 if required and change its permission if all
happen correctly.

Change-Id: I25a4392fb1e72de9c06254bc2f4d8e8f045e6ded
Signed-off-by: Richard Beneyton <richard.beneyton@intersec.com>