iopc: add weak deps to *.iop.dep files
This will fix the following error seen when switching to an older platform
branch:
platform/qkv/qkv/store.iop.c:564:16: error: ‘platform__value__custom__ft’
undeclared (first use in this function)

commit 59066e7f simply added custom to the platform.Value union. But since
store.iop only use an optional platform.Value, the platform package was
only in the weak dependencies of store.iop, and platform pkg was not added
to store.iop.dep

Also fix a potential leak

Change-Id: Ib11eb791e62e49764be8b2b083d5cee29b46838c