tests/zparser: fix invalid __str__ methods
In python 3 strings are natively encoded in UTF-8 and re-encoding then
in UTF-8 like in python 2 is broken and throws exceptions like this:

    TypeError: __str__ returned non-string (type bytes)

So we just get rid of the `.encode('utf-8')`.

(cherry picked from commit 717d833459083c45722d3250d39be7fa648194e8)
Change-Id: I50e6aae05435b78ec4b585ec2023e716b9167ded