zchk: fix link with P=asan
in lib-common 2012.2, zchk-iop use pow so we need -lm to link zchk

For some reasons, the problem only appears with P=asan (and maybe only
with some glibc versions, I have libc6 2.17-93 from debian testing)

/usr/bin/ld: .build-asan-pisco/lib-common/zchk-iop.c.zchk.lib-common.o:
undefined reference to symbol 'pow@@GLIBC_2.2.5'

Change-Id: If8c3e12b9d320093e4510bfc7ed49a0d31be6736