lib-common: fix compilation with GCC 10.
In iopc-parser.c::parse_constant_integer(), 'tk->token' of type
'iopc_tok_type_t' was implicitly converted to 'iop_cfolder_op_t'.
With GCC 10 and '-Werror=enum-conversion', a warning was raised by this
conversion:

iopc/iopc-parser.c: In function ‘parse_constant_integer’:
iopc/iopc-parser.c:686:58: error: implicit conversion from ‘iopc_tok_type_t’ to ‘iop_cfolder_op_t’ [-Werror=enum-conversion]
  686 |             if (iop_cfolder_feed_operator(pp->cfolder, tk->token) < 0)
      |                                                        ~~^~~~~~~
iopc/iopc-parser.c:699:58: error: implicit conversion from ‘iopc_tok_type_t’ to ‘iop_cfolder_op_t’ [-Werror=enum-conversion]
  699 |             if (iop_cfolder_feed_operator(pp->cfolder, tk->token) < 0)
      |

The conversion is actually not an issue because in our cases in
parse_constant_integer(), the possible values of 'tk->token' are valid
values of both 'iopc_tok_type_t' and 'iop_cfolder_op_t'.

Change-Id: Ic458c05ecdd218e0649a078f3a509a4078a047e1