[BACKPORT] core-mem: Fix possible link error on __imalloc_too_large.
This function was declared but was not implemented because it is
supposed to cause an error at compile-time when called:

  #if __GNUC_PREREQ(4, 3) || __has_attribute(error)
  __attribute__((error("you cannot allocate that much memory")))
  #endif
  extern void __imalloc_too_large(void);

But in case the compiler does not match the #if condition, it ended
up in a link error:

 /usr/bin/ld: .build-waf-debug/tools/farchc.c.1.o: in function `icheck_alloc_constant':
 /home/romain/dev/lib-common/./core-mem.h:332: undefined reference to `__imalloc_too_large'

Change-Id: Iae76f7fdfb4ad2f52f58e066c8361231995cc733
(cherry picked from commit 6c327626893dcc5a9c26afc0a81e7f9efc8bdfc2)