lib-common: fix build on clang 10.
iopc/iopc-lex.c:1534:13: error: misleading indentation; statement is not part of the previous 'if' [-Werror,-Wmisleading-indentation,Parse Issue]
            if ( ! yyg->yy_state_buf )
            ^
iopc/iopc-lex.c:1532:9: note: previous statement is here [Parse Issue]
        if ( ! yyg->yy_state_buf )
        ^

Change-Id: I33fae36d02db8f22fb8b33bb66c7422459b5035e
(cherry picked from commit 89dbedd4cca1c3fd39c897cc1685b1af5cbc7e78)