fix build with clang 8
platform/lib-common/asn1-writer.c:83:44: error: adding 'int' to a string
does not append to the string [-Werror,-Wstring-plus-int,Semantic Issue]

Change-Id: Ic4c3e568e8ec71e80c1dd6875c9112c5a55d84ba
(cherry picked from commit 14b843ca9c78d913e28248081c52189e0344dd79)