iop-json: file_flags should be an unsigned in __iop_jpack_file.
iop_jpack_file did not compile in C++ because of the following error:

 no matching function for call to '__iop_jpack_file' [Semantic Issue]
 note: candidate function not viable: no known conversion from 'int' to
 'enum file_flags' for 2nd argument [Semantic Issue]

This is because file_flags is used as a bitfield, not an 'enum
file_flags'.

Change-Id: Ief65e39c9e33cb2763de9f5728d28995258c1921